40-Validations-Pairing-lab-review/config/routes.rb
Rails.application.routes.draw do
  resources :dogs, only: [:index, :show]
  resources :employees, only: [:index, :show, :new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

40-Validations-Pairing-lab-review/app/models/dog.rb
class Dog < ApplicationRecord
    has_many :employees

    def self.sort_by_employees_count
        self.all.sort_by{|dog| dog.employees.count }
    end
end

40-Validations-Pairing-lab-review/app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :dog

    def name
        "#{self.first_name} #{self.last_name}"
    end

    validates :title, :alias, uniqueness: true
    #validates :alias, uniqueness: true
    # validates :img_url, presence: true
    validates :img_url, presence: {message: "Please add image URL to create an employee"}
    validates :first_name, length: { minimum: 2 }
end

40-Validations-Pairing-lab-review/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

40-Validations-Pairing-lab-review/app/controllers/dogs_controller.rb
class DogsController < ApplicationController

    def index
        # @dogs = Dog.all
        @dogs = Dog.sort_by_employees_count
    end

    def show #"/dogs/:id"
        @dog = Dog.find(params[:id])
    end
end

40-Validations-Pairing-lab-review/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

    def index
        @employees = Employee.all
    end

    def show #"/employees/:id"
        @employee = Employee.find(params[:id])
    end

    def new
        @employee = Employee.new
        @dogs = Dog.all
    end

    def create
        # byebug
        @employee = Employee.new(employee_params)

        if @employee.valid?
            @employee.save
            redirect_to @employee
        else
            flash[:errors] = @employee.errors.full_messages
            redirect_to new_employee_path
        end
    end

    def edit
        @employee = Employee.find(params[:id])
        @dogs = Dog.all
    end

    def update
        @employee = Employee.find(params[:id])
        @employee.update(employee_params)
        redirect_to @employee
    end

    private

    def employee_params
        params.require(:employee).permit(:first_name, :last_name, :alias, :title, :office, :img_url, :dog_id) 
    end
end

40-Validations-Pairing-lab-review/app/helpers/application_helper.rb
module ApplicationHelper
end

40-Validations-Pairing-lab-review/app/helpers/dogs_helper.rb
module DogsHelper
end

40-Validations-Pairing-lab-review/app/helpers/employees_helper.rb
module EmployeesHelper
end

40-Validations-Pairing-lab-review/app/views/dogs/index.html.erb
<h1>Dogs Index Page:</h1>

<% @dogs.each do |dog| %>
    <h4><%= link_to dog.name, dog_path(dog) %></h4>
<% end %>

40-Validations-Pairing-lab-review/app/views/dogs/show.html.erb
<h1> Dog Show page</h1>

<h4>Name: <%= @dog.name %></h4>
<h4>Age: <%= @dog.age %></h4>
<h4>Breed: <%= @dog.breed %></h4>

<h4> Employees: </h4>
<% @dog.employees.each do |employee| %>
    <h3>
        <%#= "#{employee.first_name} #{employee.last_name}" %>
        <%= employee.name %>
    </h3>
<% end %>

40-Validations-Pairing-lab-review/app/views/employees/_form.html.erb
<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <p><%= error %> </p>
    <% end %>
<% end %>


<%= form_for @employee do |f| %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %>

    <%= f.label :alias %>
    <%= f.text_field :alias %>

    <%= f.label :job_title %>
    <%= f.text_field :title %>

    <%= f.label :office %>
    <%= f.text_field :office %>

    <%= f.label :image_URL %>
    <%= f.text_field :img_url %>

    <%= f.label :dog %>
    <%= f.collection_select :dog_id, @dogs, :id, :name %>

    <%= f.submit %>


<% end %>

40-Validations-Pairing-lab-review/app/views/employees/edit.html.erb
<%= render "form" %>

40-Validations-Pairing-lab-review/app/views/employees/index.html.erb
<h3> Employee Index page </h3>

<% @employees.each do |employee| %>
   <h4>
    <%= link_to employee.name, employee_path(employee)%>
   </h4>
<% end %>

40-Validations-Pairing-lab-review/app/views/employees/new.html.erb
<%= render "form" %>

40-Validations-Pairing-lab-review/app/views/employees/show.html.erb
<h3> Employee show page</h3>

<h4>Name: <%= @employee.name %> </h4>
<h4>Alias: <%= @employee.alias %> </h4>
<h4>Title: <%= @employee.title %> </h4>
<h4>Office: <%= @employee.office %> </h4>
<img src=<%= @employee.img_url%> />

<h4>Dog: <%= link_to @employee.dog.name, dog_path(@employee.dog) %> </h4>

40-Validations-Pairing-lab-review/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DunderMifflinPetShop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>